### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by ckarwin**
I've added a class to calculate Aeff from both mono-energetic sims and the DC sims. I've cross checked the Aeff calculations with @israelmcmc response handling using the nominal response and they are in agreement. I have also cross checked with @zoglauer calculation for a mono-energetic source at 511 keV, again with very good agreement. 

I also refined the main DC class, updated/simplified the readme, and added a few sources to the source library.

### CODE REVIEW

**Comment by ckarwin** [comment]
I would like to merge this PR and move to the main branch.

**Comment by tsiegert** [comment]
Looks good to me. Can be merged.

**Comment by israelmcmc** [comment]
Sorry, I didn't have time to look at this last week. It looks good, and it's a good example to have.

The only thing is that we should not commit .pyc files. For cosipy maybe we should check for this in a pre-commit hook.

**Comment by ckarwin** [comment]
Thanks, @israelmcmc. I removed the .pyc files.

**Pull request merged**
